# Voice, Texture, Augment, 3-task
task: recon # arrange | recon 

# Data
data_root: /data2/longshen/Datasets/slakh2100_flac_redux/slakh_2bar_lpad0_hop1_norm_quant_nost_ts44_nodr
dataset_class: ArrangerDataset
content_consistent: False
content_aug: True
inst_aug: False
max_len: 768
include_ts_and_tempo: False
dur_input: False

# Trainer
result_root: /data2/longshen/Datasets/slakh2100_flac_redux/m2m_results
out_dir: slakh_2bar_quant_44/arrange_1bar/elaboration/no_pt/ep10_lr1e-4_linear
n_epoch: 10 # 20 # 50
lr: 0.0001
lr_scheduler: linear # linear | anneal | none
bs: 24
bs_test: 96
loss_type: tgt_seq # full_seq | tgt_seq
warmup_steps: 500
weight_decay: 0.01
val_check_interval: 0.25
n_gen_val_per_batch: 2
fast_dev_run: False # 5
early_stop_patience: 8
lr_anneal_patience: 4
val_gen_every_n_steps: 100
val_gen_n_samples: 20 # Doing generation for X samples in each validation loop

# Model
pt_ckpt: LongshenOu/m2m_pt
tokenizer_fp: LongshenOu/m2m_ft
lit_model_class: LitM2mLM
voice_control: True
texture_control: False
random_init: True

# Infer
infer_exp_name: recon # recon | rand_inst
infer_with: mini_valid
infer_inp_fn: ${infer_with}.txt
infer_out_fn: out_${infer_with}_${infer_exp_name}.txt
eval_out_fn: eval_${infer_with}_${infer_exp_name}.txt

# Reinst
reinst_group: demo_test
song_name: q_buweishei
inst_set: rband
model_name: elab_direct_nopt
# replace_inst: ['i-0'] # Piano reduction
# replace_inst: ['i-40', 'i-41', 'i-42'] # string trio
replace_inst: ['i-80', 'i-26', 'i-29', 'i-33'] # rock band
# replace_inst: ['i-64', 'i-40', 'i-61', 'i-26', 'i-0', 'i-44', 'i-33'] # jazz band
hist_autoregressive: True
reinst_exp_name: ${song_name}_${model_name}_${inst_set}_k${top_k}p${top_p}t${temp}n${no_repeat_token}

top_k: 20
top_p: 1.0
temp: 1.0
no_repeat_token: 0 # Set to 0 to disable no_repeat_token